name: Quality

on:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  typeccript:
    name: TypeScript
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Install
        uses: ./.github/composite-actions/install

      - name: Run typecheck
        working-directory: ./packages/lib
        run: pnpm typecheck

  oxfmt:
    name: Oxfmt
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Install
        uses: ./.github/composite-actions/install

      - name: Run format
        working-directory: ./packages/lib
        run: pnpm format
