name: Security

on:
  pull_request:
    branches:
      - main
  merge_group:
    branches:
      - main

permissions:
  actions: read
  security-events: write
  contents: read

jobs:
  vulnerabilitiy-scan-with-osv:
    name: Vulnerability Scan (OSV Scanner)
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: OSV Scanner
        uses: google/osv-scanner-action/.github/workflows/osv-scanner-reusable-pr.yml@c51854704019a247608d928f370c98740469d4b5 # v2.3.5
